/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: c4d7aae2ab9a0fcb0baf5cc57a25e10b)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	UPSTREAM_API_ORIGIN: "https://vercel-origin.worldmonitor.app";
	NODE_ENV: "production";
	RELAY_AUTH_HEADER: "x-relay-key";
	COUNTER: DurableObjectNamespace<import("./worker/entry").CounterDO>;
	SEED_CONTAINER: DurableObjectNamespace<import("./worker/entry").SeedContainer>;
	AIS_RELAY: DurableObjectNamespace<import("./worker/entry").AisRelayDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/entry");
		durableNamespaces: "CounterDO" | "SeedContainer" | "AisRelayDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "UPSTREAM_API_ORIGIN" | "NODE_ENV" | "RELAY_AUTH_HEADER">> {}
}
