// Astro's content layer needs the docs collection declared. Starlight ships
// the loader and schema; src/content/docs/ is generated by
// scripts/prepare-content.mjs and is not checked in.
import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
