/**
 * Augments the ambient `Cloudflare.Env` namespace worker-configuration.d.ts
 * (Wrangler-generated, do not edit) already opens. That file's second line
 * reads "Generated by Wrangler by running `wrangler types`" -- anything
 * added there is lost the next time someone regenerates it, so the one new
 * secret this task needs lives here instead.
 *
 * Optional: the binding only exists once someone runs
 * `wrangler secret put COUNTER_INTERNAL_HMAC_SECRET` against this Worker.
 * worker/routes/counter-read.ts treats an absent secret as a plain 401, the
 * same as any other authentication failure -- never a crash, never a fall-
 * open (task-6a brief, requirement 5 / ambiguity note 3).
 */
declare namespace Cloudflare {
  interface Env {
    COUNTER_INTERNAL_HMAC_SECRET?: string;
  }
}
